version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: farmhousepassword
      POSTGRES_DB: auth-services
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-services:
    build:
      context: ./auth-services
      dockerfile: Dockerfile
    container_name: auth-services
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: farmhousepassword
      DB_NAME: auth-services
      JWT_SECRET: 2c6e8cb3de74414a4381cc6b67eda14d810871938da4a45f9ea52cdf2747de362dcd687aa69bf747d81c4e7554e8b9cc1a68fac2937f59f845a90000681fb6f5
      JWT_EXPIRATION: 1h
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  order-services:
    build:
      context: ./order-services
      dockerfile: Dockerfile
    container_name: order-services
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: farmhousepassword
      DB_NAME: order-services
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  payment-services:
    build:
      context: ./payment-services
      dockerfile: Dockerfile
    container_name: payment-services
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: farmhousepassword
      DB_NAME: payment-services
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  product-services:
    build:
      context: ./product-services
      dockerfile: Dockerfile
    container_name: product-services
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: farmhousepassword
      DB_NAME: product-services
    ports:
      - "3004:3004"
    depends_on:
      - postgres

  store-services:
    build:
      context: ./store-services
      dockerfile: Dockerfile
    container_name: store-services
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: farmhousepassword
      DB_NAME: store-services
    ports:
      - "3005:3005"
    depends_on:
      - postgres

  user-services:
    build:
      context: ./user-services
      dockerfile: Dockerfile
    container_name: user-services
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: farmhousepassword
      DB_NAME: user-services
    ports:
      - "3006:3006"
    depends_on:
      - postgres

volumes:
  postgres_data: